bbc-on-ice
==========

'bbc-on-ice' is a SHOUTcast (ICY protocol) bridge for BBC radio streams.
It adds metadata to the stream so that media players can display it.  There are
some inherent technical limitations to how accurate the information can be
but it's definitely better to have an approximate title than nothing.

Packages
--------
Regular releases are sporadic.  git master should be stable enough.  You can get
a package with the latest development version from Archlinux's AUR.

Building and Running
--------------------
Build dependencies: go

 $ git clone https://git.janouch.name/p/bbc-on-ice.git
 $ cd bbc-on-ice
 $ go build

To run the local server:

 $ ./bbc-on-ice :8000

Streams have URLs in the following form:

 $ mpv http://localhost:8000/nonuk/sbr_low/bbc_radio_one
 $ mpv http://localhost:8000/uk/sbr_high/bbc_1xtra

Socket activation
-----------------
The provided bbc-on-ice.service and bbc-on-ice.socket should do, just change
the `ExecStart` path as needed and place the files appropriately.  Then:

 $ systemctl enable bbc-on-ice.socket
 $ systemctl start bbc-on-ice.socket

Contributing and Support
------------------------
Use https://git.janouch.name/p/bbc-on-ice to report any bugs, request features,
or submit pull requests.  `git send-email` is tolerated.  If you want to discuss
the project, feel free to join me at ircs://irc.janouch.name, channel #dev.

Bitcoin donations are accepted at: 12r5uEWEgcHC46xd64tt3hHt9EUvYYDHe9

License
-------
This software is released under the terms of the 0BSD license, the text of which
is included within the package along with the list of authors.
